name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ----------------------------------------------------------------
  # Lint Job
  # ----------------------------------------------------------------
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Cache pip so we don't reinstall everything on every run.
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install dev requirements (includes main requirements.txt)
          pip install -r requirements-dev.txt
          # Install in editable mode
          pip install -e .

      - name: Run pre-commit (lint checks)
        run: |
          pre-commit run --all-files --show-diff-on-failure

  # ----------------------------------------------------------------
  # Test Job
  # ----------------------------------------------------------------
  tests:
    name: Tests
    runs-on: ubuntu-latest

    # If you prefer to ensure lint must pass before tests run, uncomment:
    # needs: [lint]

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run tests with coverage
        run: |
          pytest --cov=swiftagent --cov-report=term-missing
